# Generated by Django 6.1.1 on 2026-09-05 09:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthArticle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('heart', 'Heart Health & Cardio'), ('nutrition', 'Nutrition & Diet'), ('mental_health', 'Mental Wellness & Stress'), ('sleep', 'Sleep & Circadian Health'), ('fitness', 'Fitness & Movement'), ('women_health', "Women's Health & Hormones"), ('pediatrics', 'Child & Infant Care'), ('preventive', 'Preventive Medicine & Longevity'), ('general', 'General Health Tips')], default='general', max_length=50)),
                ('summary', models.TextField(help_text='Short engaging summary for the feed card')),
                ('content', models.TextField(help_text='Detailed article content, health recommendations and clinical insights')),
                ('read_time', models.CharField(default='3 min read', max_length=20)),
                ('cover_image', models.URLField(blank=True, max_length=500)),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='users.doctorprofile')),
            ],
            options={
                'db_table': 'health_articles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArticleLike',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_likes', to=settings.AUTH_USER_MODEL)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='community.healtharticle')),
            ],
            options={
                'db_table': 'article_likes',
                'unique_together': {('user', 'article')},
            },
        ),
    ]
