# Generated by Django 6.1.1 on 2026-09-05 09:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='healtharticle',
            name='author_name_display',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='healtharticle',
            name='author_role_badge',
            field=models.CharField(default='Verified Medical Specialist', max_length=100),
        ),
        migrations.AddField(
            model_name='healtharticle',
            name='author_type',
            field=models.CharField(choices=[('doctor', 'Board-Certified Doctor'), ('nurse', 'Registered Nurse'), ('trainer', 'Certified Fitness/Physio Specialist'), ('nutritionist', 'Clinical Dietitian'), ('contributor', 'Health Contributor')], default='doctor', max_length=30),
        ),
        migrations.AddField(
            model_name='healtharticle',
            name='creator_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='healtharticle',
            name='earnings',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='healtharticle',
            name='is_monetized',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='healtharticle',
            name='is_verified_creator',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='healtharticle',
            name='video_url',
            field=models.URLField(blank=True, help_text='Optional YouTube or Cloudinary video tutorial URL', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='healtharticle',
            name='views_count',
            field=models.PositiveIntegerField(default=150),
        ),
        migrations.AlterField(
            model_name='healtharticle',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='users.doctorprofile'),
        ),
        migrations.AlterField(
            model_name='healtharticle',
            name='category',
            field=models.CharField(choices=[('general', 'General Health Tips'), ('nutrition', 'Nutrition & Harvard Healthy Eating'), ('heart', 'Heart Health & Cardio'), ('sleep', 'Sleep & Circadian Health'), ('fitness', 'Fitness, Movement & Exercise'), ('women_health', "Women's Health & Hormones"), ('mental_health', 'Mental Wellness & Stress'), ('pediatrics', 'Child & Infant Care'), ('preventive', 'Preventive Longevity & Vitals'), ('videos', 'Video Care Tutorials & Demonstrations')], default='general', max_length=50),
        ),
        migrations.AlterField(
            model_name='healtharticle',
            name='content',
            field=models.TextField(help_text='Detailed article content, clinical insights and protocols'),
        ),
        migrations.CreateModel(
            name='CreatorProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('professional_title', models.CharField(blank=True, help_text='e.g. Cardiologist, Registered Clinical Nurse, Certified Strength Coach', max_length=150)),
                ('bio', models.TextField(blank=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_monetization_approved', models.BooleanField(default=False)),
                ('verification_documents_uploaded', models.BooleanField(default=False)),
                ('total_views', models.PositiveIntegerField(default=0)),
                ('total_likes', models.PositiveIntegerField(default=0)),
                ('total_earned', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('pending_payout', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payout_bank_details', models.CharField(blank=True, help_text='Bank Name, Account Number, Routing/Swift', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='creator_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'creator_profiles',
            },
        ),
    ]
