# Generated by Django 6.1.1 on 2026-09-05 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_healtharticle_author_name_display_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='healtharticle',
            name='video_file',
            field=models.FileField(blank=True, help_text='Direct uploaded video file (MP4, WebM)', null=True, upload_to='community_videos/'),
        ),
    ]
