# Generated by Django 6.1.1 on 2026-09-04 19:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symptom_notes', models.TextField(blank=True)),
                ('follow_up_answers', models.JSONField(blank=True, default=dict)),
                ('severity', models.CharField(choices=[('green', 'Mild / Non-urgent'), ('yellow', 'Moderate / Requires Consultation'), ('red', 'Severe / Immediate Medical Care Needed')], default='yellow', max_length=10)),
                ('summary', models.TextField()),
                ('possible_conditions', models.JSONField(default=list)),
                ('medication_recommendations', models.JSONField(default=list)),
                ('disclaimer', models.TextField(default='DISCLAIMER: This AI-generated assessment is for informational and preliminary triage purposes only. It is NOT a medical diagnosis or clinical opinion. If you are experiencing severe symptoms, please consult a verified physician or visit an emergency room immediately.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ai_assessments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(default='General', max_length=100)),
            ],
            options={
                'db_table': 'symptoms',
                'ordering': ['category', 'name'],
            },
        ),
    ]
