# Generated by Django 6.1.1 on 2026-09-04 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_engine', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aiassessment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_assessments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aiassessment',
            name='symptoms',
            field=models.ManyToManyField(related_name='assessments', to='ai_engine.symptom'),
        ),
    ]
