# Generated by Django 6.1.1 on 2026-09-05 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiassessment',
            name='clinical_reasoning',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='aiassessment',
            name='what_to_do_and_not_do',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='aiassessment',
            name='when_to_visit_clinic',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
