# Generated by Django 6.1.1 on 2026-09-08 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0003_aiassessment_clinical_reasoning_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiassessment',
            name='severity',
            field=models.CharField(choices=[('EMERGENCY', 'Immediate 911 / Emergency Room'), ('URGENT', 'Clinic / Urgent Care within 12–24h'), ('ROUTINE', 'Doctor Visit / Monitoring'), ('SELF_CARE', 'Self-Care & Home Monitoring'), ('red', 'Emergency / Immediate Medical Care'), ('yellow', 'Urgent / Consultation Recommended'), ('green', 'Routine / Self-Care')], default='ROUTINE', max_length=20),
        ),
    ]
