# Generated by Django 6.1.1 on 2026-09-04 19:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('emergency_type', models.CharField(choices=[('cardiac', 'Chest Pain / Cardiac Alert'), ('breathing', 'Severe Respiratory Distress'), ('trauma', 'Trauma / Severe Bleeding'), ('general', 'General Urgent Crisis')], default='general', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending Duty Doctor'), ('assigned', 'Duty Doctor Assigned'), ('resolved', 'Resolved')], default='pending', max_length=20)),
                ('location_address', models.CharField(blank=True, max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'emergency_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
