# Generated by Django 6.1.1 on 2026-09-04 19:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('lab_report', 'Lab Test Report'), ('prescription', 'Doctor Prescription'), ('scan', 'Medical Imaging / Scan'), ('other', 'Other Document')], default='lab_report', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(blank=True, null=True, upload_to='patient_documents/')),
                ('cloudinary_url', models.URLField(blank=True, max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'medical_documents',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
