# Generated by Django 6.1.1 on 2026-09-08 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicaldocument',
            name='title',
            field=models.CharField(blank=True, default='Medical Record', max_length=200),
        ),
    ]
